id = "fountain"
name = "Fountain"
version = "0.0.9"
schema_version = 1
authors = ["Joop Kiefte <joop@kiefte.net>"]
description = "A Zed extension adding Fountain support"
repository = "https://github.com/LaPingvino/zed-fountain"

[grammars.fountain]
repository = "https://github.com/LaPingvino/tree-sitter-fountain"
commit = "2f740be5f3c4d85b2864e02285986797a2904e20"
