id = "fountain"
name = "Fountain"
version = "0.0.9"
schema_version = 1
authors = ["Joop Kiefte <joop@kiefte.net>"]
description = "A Zed extension adding Fountain support"
repository = "https://github.com/LaPingvino/zed-fountain"

[grammars.fountain]
repository = "https://github.com/LaPingvino/tree-sitter-fountain"
commit = "ccf57ef62e844a9b77404bc761f2057cf560ca1a"
