id = "fountain"
name = "Fountain"
version = "0.0.7"
schema_version = 1
authors = ["Joop Kiefte <joop@kiefte.net>"]
description = "A Zed extension adding Fountain support"
repository = "https://github.com/LaPingvino/zed-fountain"

[grammars.fountain]
repository = "https://github.com/LaPingvino/tree-sitter-fountain"
commit = "ebb5a9b055fd6fee4827b81c33182d8a9ad1b784"
