id = "fountain"
name = "Fountain"
version = "0.0.4"
schema_version = 1
authors = ["Joop Kiefte <joop@kiefte.net>"]
description = "A Zed extension adding Fountain support"
repository = "https://github.com/LaPingvino/zed-fountain"

[grammars.fountain]
repository = "https://github.com/LaPingvino/tree-sitter-fountain"
commit = "66adc2cef8857c31eeb2c6a4f8d87ee5a49fd5aa"
