id = "fountain"
name = "Fountain"
version = "0.0.5"
schema_version = 1
authors = ["Joop Kiefte <joop@kiefte.net>"]
description = "A Zed extension adding Fountain support"
repository = "https://github.com/LaPingvino/zed-fountain"

[grammars.fountain]
repository = "https://github.com/LaPingvino/tree-sitter-fountain"
commit = "2e9d18969f0da7b7df0e3909582ac6b097c971bf"
