id = "fountain"
name = "Fountain"
version = "0.0.6"
schema_version = 1
authors = ["Joop Kiefte <joop@kiefte.net>"]
description = "A Zed extension adding Fountain support"
repository = "https://github.com/LaPingvino/zed-fountain"

[grammars.fountain]
repository = "https://github.com/LaPingvino/tree-sitter-fountain"
commit = "8717c3dfd725860f873fc1300405ffce6e6268c6"
