id = "fountain"
name = "Fountain"
version = "0.2.0"
schema_version = 1
authors = ["Joop Kiefte <joop@kiefte.net>"]
description = "A Zed extension adding Fountain support"
repository = "https://github.com/LaPingvino/zed-fountain"

[grammars.fountain]
repository = "https://github.com/LaPingvino/tree-sitter-fountain"
commit = "2d943e1e3ec8426ab4ae2d5d27c799a5760ebfdb"

[language_servers.lexington-lsp]
name = "Lexington LSP"
command = "./bin/lexington"
args = ["--lsp"]
